### ISSUE TITLE
[bamutils  count]  bai file missing

### ISSUE THREAD

**Issue by darked89** [ngsutils/ngsutils#1]
When running 

bamutils  count  -gtf foo.gtf bar.bam | less

I am getting:
Error: Missing bam index (bai) file

Problem is that it expects bar.bam.bai, but default for picard BAM indexes is bar.bai

I can link all  barXYZ.bai to  barXYZ.bam.bai, but then it probably makes more sense to make ngsutil Picard friendly.

Hope it helps,

Darek Kedra

**Comment by mbreese** [comment]
Unfortunately, this isn't my call - this is from the underlying pysam library, which follows the samtools convention of bar.bam.bai.
