### ISSUE TITLE
Regarding Installation

### ISSUE THREAD

**Issue by jaikharb** [ngsutils/ngsutils#10]
i try to install Ngsutils using Git clone but not able to run the bamutils, bedutils, fastqutils, and gtfutils  commands. ther executables are not generated and not seen in any folder. Please help me to install ngsutils properly.

**Comment by mbreese** [comment]
I'm commenting late on this, but in case anyone has the same problem - the bamutils/bedutils/fastqutils/gtfutils commands are in the bin/ directory. They are symlinked to the file 'bin/ngsutils', which is the same script for each of the sub-tools.

When you checkout the package (git clone), the easiest thing to do is run "make". This sets up the dependencies for the package. You can then call the scripts in bin/*, or, symlink the scripts to /usr/local/bin, or another place in your path.
