### ISSUE TITLE
Installation fails with Error 1

### ISSUE THREAD

**Issue by nicolazilio** [ngsutils/ngsutils#16]
When I run make for ngsutils, I get the following error message

/ngsutils$ make
./init.sh
./init.sh: line 16: venv/bin/activate: No such file or directory
make: *** [init] Error 1

Does anybody now how to solve this?

Thanks

**Comment by mtandon09** [comment]
See Issue #12. Basically, try changing the interpreter to bash for init.sh and the ngsutils wrapper script in the bin folder after compilation (i.e. change the first line from "#!/bin/sh" to "#!/bin/bash")

**Comment by mbreese** [comment]
Should have been fixed with a prior commit.
