### ISSUE TITLE
gtfutils - fromgff3 command missing from menu

### ISSUE THREAD

**Issue by colindaven** [ngsutils/ngsutils#17]
Hi,

thanks for the great software.

The command fromgff seems to be missing from the menu, at least for this version

cheers,
Colin

gtfutils
Usage: gtfutils COMMAND

Commands
  General
    add_isoform - Appends isoform annotation from UCSC isoforms file
    add_reflink - Appends isoform/name annotation from RefSeq/refLink
    add_xref    - Appends name annotation from UCSC Xref file
    annotate    - Annotates genomic positions based on a GTF model
    filter      - Filter annotations from a GTF file
    genesize    - Extract genomic/transcript sizes for genes
    junctions   - Build a junction library from FASTA and GTF model
    query       - Query a GTF file by coordinates

  Conversion
    tobed       - Convert a GFF/GTF file to BED format

Run 'gtfutils help CMD' for more information about a specific command
ngsutils 0.5.5-2232b67

**Comment by mbreese** [comment]
fromgff now included...
