### ISSUE TITLE
error when using fastqutils tile

### ISSUE THREAD

**Issue by ecastron** [ngsutils/ngsutils#2]
Hi guys,

I'm trying to split reads from a PacBio run into shorter reads of 100bp non overlapping. I'm using the following command line:

fastqutils tile -len 100 -offset 100 s002_16s.fastq s002_16s_split.fastq 

But I get the following error message:

Traceback (most recent call last):
  File "/groups/cbi/ngsutils/bin/..//ngsutils/fastq/tile.py", line 100, in <module>
    last = none
NameError: name 'none' is not defined

I've tried different machines (mac and linux) and different fastq files (from PacBio and Illumina).

Any clue on what might be occurring?

Thanks

Eduardo

**Comment by mbreese** [comment]
Fixed... was an old typo.
