### ISSUE TITLE
bugs with Installation and run

### ISSUE THREAD

**Issue by yifangt** [ngsutils/ngsutils#21]
Hello:
I cloned ngsutils, but I had problem to install it:
__$ make__
*******************************************************************************************************************
_./init.sh_
_./init.sh: 3: [: unexpected operator_
_Initializing virtualenv folder (venv)_
_./init.sh: 13: ./init.sh: $HOME/downloads/ngsutils/support/virtualenv.py: Permission denied_
_./init.sh: 16: .: Can not open venv/bin/activate_
_Makefile:3: recipe for target 'init' failed_
_make: *** [init] Error 2_
*******************************************************************************************************************
unless I change the permission of the file:

__$ chmod 755 $HOME/downloads/ngsutils/support/virtualenv.py__
__$ make__
......
Then, whenever I run it I have following lines at the beginning. It seems the tool eventually works fine but I am nervous with the result. Only fastqutils was tested with real data so far. Others were tested with command options without real data yet, but same message. 
*******************************************************************************************************************
_$HOME/downloads/ngsutils/bin/fastqutils: 22: [: sort: unexpected operator_
_$HOME/downloads/ngsutils/bin/fastqutils: 30: [: fastq: unexpected operator_
_$HOME/downloads/ngsutils/bin/fastqutils: 59: [: sort: unexpected operator_
_$HOME/downloads/ngsutils/bin/fastqutils: 75: [: sort: unexpected operator_
_$HOME/downloads/ngsutils/bin/fastqutils: 81: [: sort: unexpected operator_
*******************************************************************************************************************
Not sure those lines are  errors or just warnings with the programs. 
Could you please clarify above 2 issues, if I missed anything?
Thank you!
Yifang

**Comment by mbreese** [comment]
Should be fixed in recent updates.
