### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by anusurendra** [ngsutils/ngsutils#22]
Hi,

I am trying to install the ngsutils. However, when I run PYTHON3.4 make, I get the following error:
./init.sh
./init.sh: 3: [: python3.4: unexpected operator
./init.sh: 18: [: Linux: unexpected operator
Requires Python 2.6+

Thanks in advance for you help,
Anu

**Comment by mbreese** [comment]
Should be fixed with a fresh git pull.
