### ISSUE TITLE
Is it possible to check for .bai files and not just .bam.bai files ?

### ISSUE THREAD

**Issue by jguhlin** [ngsutils/ngsutils#3]
-bash-4.1$ bamutils count -bin 10000 -fpkm -norm all HM101.recalibrated.bam
Error: Missing bam index (bai) file: HM101.recalibrated.bam

However, the HM101.recalibrated.bai file is present. I had to copy HM101.recalibrated.bai to HM101.recalibrated.bam.bai to get it to work. 

Can it also check for .bai files where the extension has been replaced, rather than added to? All of our bai files are named that way and work with most other tools.

Once I fixed that issue, it works.

**Comment by mbreese** [comment]
Old issue, I know, but for documentation purposes - no, I can't fix that check. Unfortunately, that is required by the pysam library. Like most samtools/htslib based libraries, it tries to open .bam.bai, as opposed to the .bai filenames that other libraries try to open.
